/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fromemakeone;

/**
 *
 * @author 12
 */
public class CakePic extends javax.swing.JFrame {

    /**
     * Creates new form CakePic
     */
    public CakePic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        pinapple = new javax.swing.JRadioButton();
        banan = new javax.swing.JRadioButton();
        blackforest = new javax.swing.JRadioButton();
        lemon = new javax.swing.JRadioButton();
        coffie = new javax.swing.JRadioButton();
        fruth = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        lemonp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(767, 1100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 248, 151));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pinapple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pinapple.setText("pineapple-cake");
        jPanel1.add(pinapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        banan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        banan.setText("Banana-cake");
        jPanel1.add(banan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        blackforest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        blackforest.setText("Black-forest-cake");
        jPanel1.add(blackforest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        lemon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lemon.setText("Lemon-cake");
        lemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonActionPerformed(evt);
            }
        });
        jPanel1.add(lemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));

        coffie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        coffie.setText("Coffie Cake");
        jPanel1.add(coffie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        fruth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fruth.setText("fruth cake");
        fruth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruthActionPerformed(evt);
            }
        });
        jPanel1.add(fruth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fromemakeone/Funfetti-cake-100x100.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fromemakeone/Coffee-cake-100x100.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 100, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fromemakeone/vanilla-cake h100 w100.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 100, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fromemakeone/Banana-cake-h100 w100.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fromemakeone/Black-forest-cake-100x100.jpeg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 100, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fromemakeone/Lemon-cake-100x100.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 100, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fromemakeone/cake w 540 h300.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 540, 260));

        next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        next.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nextKeyPressed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, 90, 40));

        lemonp.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lemonp.setText("400");
        jPanel1.add(lemonp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 70, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("550");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 70, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("450");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 70, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("600");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 70, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("700");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 70, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("750");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 790, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lemonActionPerformed

    private void fruthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fruthActionPerformed

    private void nextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nextKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_nextKeyPressed
    String name="", price="";
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        //String name="", price="";
        if (lemon.isSelected()) {
            name = lemon.getText();
            price = lemonp.getText();
//            price = String.valueOf(400);

        }
        else if  (banan.isSelected()) {
            name = banan.getText();
            price = jLabel13.getText();
//            price = String.valueOf(400);

        }
       else  if (pinapple.isSelected()) {
            name = pinapple.getText();
            price = jLabel12.getText();
//            price = String.valueOf(400);

        }
       else  if (blackforest.isSelected()) {
            name = blackforest.getText();
            price = jLabel11.getText();
//            price = String.valueOf(400);

        }
        else  if (coffie.isSelected()) {
            name = coffie.getText();
            price = jLabel10.getText();
//            price = String.valueOf(400);

        }else  if (fruth.isSelected()) {
            name = fruth.getText();
            price = jLabel5.getText();
//            price = String.valueOf(400);

        }
//        

        Invoice n = new Invoice(name,"","", price);
        

        n.setVisible(true);

    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CakePic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CakePic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CakePic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CakePic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CakePic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton banan;
    private javax.swing.JRadioButton blackforest;
    private javax.swing.JRadioButton coffie;
    private javax.swing.JRadioButton fruth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton lemon;
    private javax.swing.JLabel lemonp;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton pinapple;
    // End of variables declaration//GEN-END:variables
}
