/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fromemakeone;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class ProductInformation extends javax.swing.JFrame {

    String pnams;
    String pids;
    String stocks;
    String unitps;

    //class make korlam
    String driver = "com.mysql.jdbc.Driver";
    String url = "jdbc:mysql://localhost:3306/inventory";
    Connection con;
    Statement stm;
    PreparedStatement pprds;
    String sqls;//quary rakha hoba
    DefaultTableModel dtm = new DefaultTableModel();
    ResultSet rs;

    //sql drive dora jono
    public  void myDrive() {
        try {
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "12345");

        } catch (ClassNotFoundException cnf) {
            System.out.println(cnf);
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, sqle);
        }

    }

    String Sid, po, st, upr, name, price;

    public ProductInformation() {
        initComponents();
    }

    public ProductInformation(String namee, String pprice) {
        this.name = namee;
        this.price = pprice;
//    p();
        initComponents();
        Pnam.setText(name);
        Uprice.setText(price);

    }

    void p() {
        Pnam.setText(name);
        Uprice.setText(price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lll = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pnam = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Uprice = new javax.swing.JTextField();
        save = new java.awt.Button();
        button2 = new java.awt.Button();
        update = new java.awt.Button();
        delet = new java.awt.Button();
        lll1 = new javax.swing.JLabel();
        Date sd= new Date();
        String stdDate =(sd.getDate())+"-"+(sd.getMonth()+1)+"-"+
        (1900+sd.getYear());

        d = new javax.swing.JTextField(stdDate);
        jScrollPane2 = new javax.swing.JScrollPane();
        udat = new javax.swing.JTable();
        show = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 248, 151));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAKE O CLOCK INFORMATION");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 370, 40));

        lll.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lll.setText("Product Id");
        jPanel1.add(lll, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 84, 94, -1));

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 85, 274, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Product Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 169, 106, -1));

        Pnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnamActionPerformed(evt);
            }
        });
        jPanel1.add(Pnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 170, 274, -1));
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 219, 274, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Stock");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 213, 106, 29));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 260, 106, 29));
        jPanel1.add(Uprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 266, 274, -1));

        save.setActionCommand("Save");
        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        save.setLabel("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 120, 30));

        button2.setBackground(new java.awt.Color(204, 204, 204));
        button2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button2.setLabel("New");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 150, 30));

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        update.setLabel("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 130, -1));

        delet.setBackground(new java.awt.Color(204, 204, 204));
        delet.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        delet.setLabel("Delet");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });
        jPanel1.add(delet, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 130, -1));

        lll1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lll1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lll1.setText("Date");
        jPanel1.add(lll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 52, 94, -1));

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 53, 274, -1));

        udat.setModel(dtm);
        udat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                udatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(udat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 295, 670, 162));

        show.setBackground(new java.awt.Color(204, 204, 204));
        show.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 120, -1));

        next.setBackground(new java.awt.Color(204, 204, 204));
        next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 130, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fromemakeone/270w 280h cake.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 280));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Place Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 147, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("File");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -2, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//public  String m() {
//        String st = pid.getText();
//       Invoice in = new Invoice();
//       return st;
//    }

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_pidActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

//data patanor jono from thaka data base a
        myDrive();
//product id duplicat hoba na

        String s = "";
        try {
            stm = con.createStatement();
            rs = stm.executeQuery("select product_id from product " + "where product_id=" + Integer.parseInt(pid.getText()) + "");
            while (rs.next()) {
                s = rs.getString("product_id");
            }
            if (s.equals(pid.getText())) {
                JOptionPane.showMessageDialog(null, "exits");
                pid.requestFocus();
            } else {
                sqls = "Insert into product values("
                        + Integer.parseInt(pid.getText()) + ",'" + Pnam.getText() + "',"
                        + Integer.parseInt(stock.getText()) + ","
                        + Integer.parseInt(Uprice.getText()) + ")";
                try {
                    stm = con.createStatement();
                    System.out.println(con);
                    stm.executeUpdate(sqls);
                    JOptionPane.showMessageDialog(null, "successfull");

                } catch (SQLException sqles) {
                    JOptionPane.showMessageDialog(null, sqles);
                }
            }
        } catch (Exception e) {
        }

///
//        Sid = pid.getText();
//        po = Pnam.getText();
//        st = stock.getText();
//        upr= Uprice.getText();
//        
//        ///// validation start
//        
//        if (pid.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Product id is Required");
//            
//            pid.requestFocus();
//        }
//        else {
//            try {
//                Integer.parseInt(st);
//                Integer.parseInt(upr);
//                Invoice obj = new Invoice(Sid,po,st,upr);
//                obj.setVisible(true);
//            } catch (NumberFormatException e) {
//                //JOptionPane.showMessageDialog(null, e);
//                //e.printStackTrace();
//                System.out.println(e.getCause());
//                
//                stock.requestFocus();
//            }
//        }
//        

    }//GEN-LAST:event_saveActionPerformed

    private void PnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnamActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        //price and stock update
        myDrive();
        try {
            sqls = "update product set " + "stock=?,unit_price=? where " + "product_id ="
                    + Integer.parseInt(pid.getText() + "");
            pprds = con.prepareStatement(sqls);
            pprds.setString(1, stock.getText());
            pprds.setString(2, Uprice.getText());
            pprds.executeUpdate();
            JOptionPane.showMessageDialog(null, "updateDone");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        showActionPerformed(evt);
    }//GEN-LAST:event_updateActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        //table shoe korsa

        myDrive();
        try {
            sqls = "select product_id,product_name,stock,unit_price from product";
            stm = con.createStatement();
            rs = stm.executeQuery(sqls);
            Vector<String> header = new Vector<String>();
            header.add("Product Id");
            header.add("Product name");
            header.add("Stock");
            header.add("Unit price");
            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (rs.next()) {
                Vector<Object> row = new Vector<Object>();
                row.add(rs.getString("product_id"));
                row.add(rs.getString("product_name"));
                row.add(rs.getString("stock"));
                row.add(rs.getString("unit_price"));
                data.add(row);
            }
            dtm.setDataVector(data, header);
        } catch (SQLException exp) {
            System.out.println("exp");
        }

    }//GEN-LAST:event_showActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
        //delet korar jono 

        myDrive();
        if (JOptionPane.showConfirmDialog(null, "do you want to" + "delets this Item?") == 0) {
            try {

                sqls = "delete from product where product_id="
                        + Integer.parseInt(pid.getText());
                pprds = con.prepareStatement(sqls);
                pprds.executeUpdate();
                JOptionPane.showMessageDialog(null, "delet hoya gasa ");
            } catch (SQLException ex) {
                Logger.getLogger(ProductInformation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        showActionPerformed(evt);
    }//GEN-LAST:event_deletActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        
//        next button
        cakePIK n = new cakePIK();

        n.setVisible(true);

        


    }//GEN-LAST:event_nextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        pnams = Pnam.getText();
        pids = pid.getText();
        stocks = stock.getText();
        unitps = Uprice.getText();
        Invoice n = new Invoice(pnams, pids, stocks, unitps);
        n.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void udatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udatMouseClicked
        // TODO add your handling code here:
        myDrive();
        try {
            sqls = "select product_id,product_name,stock,unit_price from product";
            stm = con.createStatement();
            rs = stm.executeQuery(sqls);
            int index = udat.getSelectedRow();
            pid.setText(udat.getValueAt(index, 0).toString());
            Pnam.setText(udat.getValueAt(index, 1).toString());
            stock.setText(udat.getValueAt(index, 2).toString());
            Uprice.setText(udat.getValueAt(index, 3).toString());
        } catch (SQLException exp) {
            System.out.println("exp");
        }
    }//GEN-LAST:event_udatMouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pnam;
    private javax.swing.JTextField Uprice;
    private java.awt.Button button2;
    private javax.swing.JTextField d;
    private java.awt.Button delet;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JLabel lll;
    private javax.swing.JLabel lll1;
    private javax.swing.JButton next;
    private javax.swing.JTextField pid;
    private java.awt.Button save;
    private javax.swing.JButton show;
    private javax.swing.JTextField stock;
    private javax.swing.JTable udat;
    private java.awt.Button update;
    // End of variables declaration//GEN-END:variables
}
